### ISSUE TITLE
Merge with serde-xml-rs?

### ISSUE THREAD

**Issue by pcarleton** [punkstarman/serde-xml#13]
Hi! 

I saw this project and it looks like it's serialization implementation is more complete than the one in serde-xml-rs, and that you're a maintainer on both projects.  Would it be possible to replace the serialization in that crate with this implementation?

I started looking into fixing some of the issues with nested structs in serde-xml-rs before I noticed this project.

I'll plan on using this directly since I can't find it on crates.io for the time being, but let me know if you have plans for merging or if I could help in some way.

**Comment by punkstarman** [comment]
@pcarleton, thanks for noticing :smile: 
I have used this project as a sandbox of sorts in order to experiment and then try to replicate successful ideas in serde-xml-rs. Some parts have already made their way there. Others, like the serialization, haven't yet.

I have been hesitant to make breaking changes, but I think that it is time to do so.

**Comment by pcarleton** [comment]
Ah that makes sense!

I agree, a breaking change sounds great!  As far as I can tell serialization is pretty broken in the existing package, so replacing it with what you've got here would be great.  I think a new version number should help prevent any harm for existing users.
